### ISSUE TITLE
[1.12.2] Strange texture artifact on model

### ISSUE THREAD

**Issue by codetaylor** [gottsch/gottsch-minecraft-FastLadder#5]
FastLadder: 1.0.7

I'm not sure if that artifact on the model is intentional... I think it looks better without it. :)

# Before
![2017-12-09_17 23 55](https://user-images.githubusercontent.com/1240716/33801135-fe9e6f9a-dd05-11e7-9d21-a59c22ce7c1b.png)

# After
![2017-12-09_17 20 31](https://user-images.githubusercontent.com/1240716/33801133-f6768d5c-dd05-11e7-85b1-59fc8eef0378.png)

**Comment by gottsch** [comment]
The artifact was intentional. I was trying to represent all the ingredients in the model. But I agree, without looks better. I'll pull in your changes.
